version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo Building the React application...
      - npm run build

  post_build:
    commands:
      - echo Build complete.

artifacts:
  base-directory: build
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
